### ISSUE TITLE
How can i search something in docs

### ISSUE THREAD

**Issue by povgen** [anegostudios/vsapi#13]
Hey may be you could add the searching om the page. It would be good
https://github.com/dotnet/docfx/discussions/8577

**Comment by tyronx** [comment]
https://apidocs.vintagestory.at/api/index.html already has a search field

**Comment by povgen** [comment]
Yes I see it. But  it's searching only by class names. Would be great if was possible to do searching by methods and fields in class.
![image](https://github.com/anegostudios/vsapi/assets/31857318/9148dc8b-a445-4020-88d8-8c2502c18d69)
