### ISSUE TITLE
missing Cairo

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [anegostudios/vsapi#2]
Hi, Perhaps you forgot to put ".. \Cairo\Cairo.csproj", or forgot to remove from dependencies?

VisualStudio 2017 - C#

**Comment by blakdragan7** [comment]
you must define VINTAGE_STORY as an environment variable for it to compile. It's a quirk of the mod template I used for this. 
i.e. my VINTAGE_STORY=%APPDATA%\Vintagestory

**Comment by Yrij-Zhavoronkov** [comment]
not actual

**Comment by Yrij-Zhavoronkov** [comment]
not actual

------ Исходное сообщение ------
От: "Jonathon Copeland" ***@***.***>
Кому: "anegostudios/vsapi" ***@***.***>
Копия: "Юрий Жаворонков" ***@***.***>; "Author" 
***@***.***>
Отправлено: 03.07.2021 7:54:48
Тема: Re: [anegostudios/vsapi] missing Cairo (#2)
