### ISSUE TITLE
Confusing BehaviorDecor CanAttachBlockAt handler order

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/vsapi#9]
BehaviorDecor has the following [line](https://github.com/anegostudios/vsessentialsmod/blob/cdeaf3e910491a0c16e2fc8748e33f6ac8bfff81/BlockBehavior/BehaviorDecor.cs#L81). `this.block` is the decor block. The decor hasn't been placed yet, so `this.block` is not at `pos`. Instead the attaching block (what the decor is going to be attached to) is there.
```
                    var iad = this.block.GetInterface<IAcceptsDecor>(world, pos);
```

This causes `Block.GetInterface` to search in the following order for something that implements `IAcceptsDecord`:
1. The decor block that's getting placed (none of them currently implement `IAcceptsDecor`).
2. The block behaviors of the decor block that's getting placed (none of them currently implement `IAcceptsDecor`).
*Skips over the attaching block.*
*Skips over the attaching block behaviors.*
3. The block entity of the attaching block (`BlockEntityMicroBlock` is the only thing that currently implements `IAcceptsDecor`).
4. The block entity behaviors of the attaching block.

It doesn't make sense to try to search the decor block and its behaviors for `IAcceptsDecor`, because if one wanted the decor block to have different placement behavior, one could just override `TryPlaceBlock`. It would make more sense if `attachingBlock.GetInterface<IAcceptsDecor>(world, pos)` was used. Then the search order would be:
1. The attaching block.
2. The block behaviors of the attaching block.
3. The block entity of the attaching block.
4. The block entity behaviors of the attaching block.

Additionally, it would good to improve the documentation for [Block.GetInterface](https://github.com/anegostudios/vsapi/blob/e78624b6eee6920e45edcd25ba94e8199b2193af/Common/Collectible/Block/Block.cs#L2433). Is `pos` expected to be the position of a block of the same type, or is it okay for `pos` to point to a different block type like the decor behavior is doing? How does `Block.GetInterface` relate to [IBlockAccessor.GetInterface](https://github.com/anegostudios/vsapi/blob/e78624b6eee6920e45edcd25ba94e8199b2193af/Common/API/IBlockAccessor.cs#L307)? Is `Block.GetInterface` supposed to be an optimized version of `IBlockAccessor.GetInterface` (returns the same value) when one already knows the block type at the position?

Finally, please make it easier for attaching blocks to reject specific attachments. Please change these [lines](https://github.com/anegostudios/vsessentialsmod/blob/cdeaf3e910491a0c16e2fc8748e33f6ac8bfff81/BlockBehavior/BehaviorDecor.cs#L90) (replace second occurrence of `attachingBlock` with `blockToPlace`:
```
                    if (!attachingBlock.CanAttachBlockAt(world.BlockAccessor, attachingBlock, pos, blockSel.Face) || mat == EnumBlockMaterial.Snow || mat == EnumBlockMaterial.Ice)
                    {
                        failureCode = "decorrequiressolid";
                        return false;
                    }
```
To this:
```
                    if (!attachingBlock.CanAttachBlockAt(world.BlockAccessor, blockToPlace, pos, blockSel.Face) || mat == EnumBlockMaterial.Snow || mat == EnumBlockMaterial.Ice)
                    {
                        failureCode = "decorrequiressolid";
                        return false;
                    }
```

**Comment by tyronx** [comment]
Ouch, thanks for the report, will be fixed in pre5. `pos` needs to be the position where you want to get the interface from. It would not make sense to have that point to a different block.


> How does Block.GetInterface relate to IBlockAccessor.GetInterface?

Now as you mentioned this, `IBlockAccessor.GetInterface` looks redundant to me. It did the same thing, pretty much. I will delete it.
